"""add image url to products

Revision ID: 81ca58c3f349
Revises: f3ab9a2dc19b
Create Date: 2026-07-20 13:04:38.914996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ca58c3f349'
down_revision: Union[str, Sequence[str], None] = 'f3ab9a2dc19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
