"""add schema constraints and indexes

Revision ID: f3ab9a2dc19b
Revises: 2a807872274c
Create Date: 2026-07-19 16:12:40.095760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ab9a2dc19b'
down_revision: Union[str, Sequence[str], None] = '2a807872274c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_inventory_warehouse_variant', 'inventory', ['warehouse_id', 'product_variant_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_orders_customer_status', 'orders', ['customer_id', 'status'], unique=False)
    op.create_index('ix_outbox_status_created', 'outbox_events', ['status', 'created_at'], unique=False)
    op.create_index('ix_payments_order_status', 'payments', ['order_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_order_status', table_name='payments')
    op.drop_index('ix_outbox_status_created', table_name='outbox_events')
    op.drop_index('ix_orders_customer_status', table_name='orders')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_inventory_warehouse_variant', table_name='inventory')
    # ### end Alembic commands ###
